#!/bin/bash

# Start rabbit
systemctl start rabbitmq-server.service 

# Make sure root has the cookie
echo waiting for rabbit to start and make a cookie
while [[ ! -e /var/lib/rabbitmq/.erlang.cookie ]]; do sleep 0.1; done
cp /var/lib/rabbitmq/.erlang.cookie ~/

# enable visualisation
rabbitmq-plugins  enable --online rabbitmq_management
rabbitmq-plugins  enable --online rabbitmq_management_visualiser

# and ensure we have an admin
/usr/sbin/rabbitmqctl add_user admin dockeradmin
/usr/sbin/rabbitmqctl set_user_tags admin administrator
/usr/sbin/rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"

# and a boss setup too
/usr/sbin/rabbitmqctl add_vhost boss
/usr/sbin/rabbitmqctl add_user boss boss
/usr/sbin/rabbitmqctl set_permissions -p boss boss '.*' '.*' '.*'

